os: linux
dist: bionic

language: node_js
node_js:
  - "12"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  # Use Chromium instead of Chrome.
  # - export CHROME_BIN=chromium-browser
  # build library
  - npm run build -- weather-gauges
  - npm run build -- demo
  # test both library and demo page
  - npm run test -- weather-gauges --watch=false --progress=false --browsers=ChromeHeadless --reporters=kjhtml
  - npm run test -- demo --watch=false --progress=false --browsers=ChromeHeadless --reporters=kjhtml
  # run e2e tests
  # - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
